learnpathology/urls.py
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

import learnpathology.views
import slide.views

urlpatterns = [
    path('', learnpathology.views.index, name='frontpage'),
    path('privacy/', learnpathology.views.privacy_info, name='privacy'),
    path('viewer/<int:slide_id>/', slide.views.whole_slide_viewer, name="view_wsi"),
    path('viewer/tile/<int:slide_id>/<int:osd_level>/<int:x>/<int:y>/', slide.views.tile, name="tile"),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('multiple_choice/', include('multiple_choice.urls')),
    path('slide/', include('slide.urls')),
    path('tag/', include('tag.urls')),
    path('course/', include('course.urls')),
    path('task/', include('task.urls')),
    path('comparison/', include('comparison.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('free_text/', include('free_text.urls')),
    path('click_question/', include('click_question.urls')),
    path('one_to_one/', include('one_to_one.urls')),
    path('annotation_task/', include('annotation_task.urls')),

    path('one_column/', learnpathology.views.test_one_column),
    path('two_column/', learnpathology.views.test_two_column),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_FEIDE_LOGIN:
    urlpatterns += [path('accounts/', include('feide.urls')),]
    #urlpatterns += [path('accounts/', include('allauth.urls')),]

urlpatterns += [
    # Define specific paths (can be used with {% url %} tag
    # path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    # path('privacy/', views.flatpage, {'url': '/privacy/'}, name='privacy'),

    # Or, use this 'catchall' pattern for all flatpages
    re_path(r'^(?P<url>.*/)$', views.flatpage),
]

multiple_choice/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from multiple_choice import views

app_name = 'multiple_choice'
urlpatterns = [
    path('do/<int:task_id>/<int:course_id>/<int:slide_id>', views.do, name='do'),
    path('new/<int:slide_id>/', views.new, name='new'),
    path('new/<int:slide_id>/<int:course_id>', views.new, name='new'),
    path('edit/<int:task_id>/', views.edit, name='edit'),
    path('edit/<int:task_id>/<int:course_id>', views.edit, name='edit'),
]

tag/urls.py
from django.urls import path, include
from tag import views

app_name = 'tag'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('edit/<int:tag_id>/', views.edit, name='edit'),
    path('delete/<int:tag_id>/', views.delete, name='delete'),
]

multiple_choice/models.py
from django.db import models
from slide.models import Slide, AnnotatedSlide
from task.models import Task


class MultipleChoice(models.Model):
    """
    A multiple choice exercise task
    """
    task = models.OneToOneField(Task, on_delete=models.CASCADE)
    question = models.CharField(max_length=2048)
    instructions = models.CharField(max_length=2048, default='Choose the correct answer(s)')
    explanation = models.CharField(max_length=2048, blank=True)


class Choice(models.Model):
    """
    A choice in a multiple choice task
    """
    task = models.ForeignKey(MultipleChoice, on_delete=models.CASCADE)
    text = models.CharField(max_length=512)
    correct = models.BooleanField()


class RandomMCChoice(models.Model):
    """
    A choice in a RandomMultipleChoice task
    """
    slide = models.ForeignKey(Slide, on_delete=models.CASCADE)
    text = models.CharField(max_length=512)
    correct = models.BooleanField()

multiple_choice/forms.py
from django.forms import ModelForm, ModelMultipleChoiceField, Textarea, Select, SelectMultiple, ModelChoiceField
from multiple_choice.models import Choice, MultipleChoice
from task.models import Task
from tag.models import Tag



class ChoiceForm(ModelForm):
    class Meta:
        model = Choice
        fields = ['text', 'correct']
        labels = {
            'text': ('Choice text'),
            'correct': ('Correct?'),
        }
        widgets = {
            'text': Textarea(attrs={'rows': 1, 'cols': 67, 'resize': 'none'}),
        }


class MultipleChoiceForm(ModelForm):
    class Meta:
        model = MultipleChoice
        fields = ['question', 'instructions', 'explanation']
        labels = {
            'question': 'Question',
            'instructions': 'Instructions',
            'explanation': 'Explanation of answer'
        }
        widgets = {
            'question': Textarea(attrs={'rows': 1, 'cols': 70, 'resize': 'none'}),
            'instructions': Textarea(attrs={'rows': 1, 'cols': 70}),
            'explanation': Textarea(attrs={'rows': 10, 'cols': 70}),
        }

multiple_choice/views.py
from django.contrib import messages
from django.db import transaction
from django.forms import formset_factory, modelformset_factory
from django.shortcuts import render, redirect, get_object_or_404

from task.common import process_new_task_request, process_edit_task_request, \
    setup_common_new_task_context, setup_common_edit_task_context
from slide.views import slide_cache
from task.forms import TaskForm
from multiple_choice.models import MultipleChoice, Choice
from multiple_choice.forms import MultipleChoiceForm, ChoiceForm
from course.models import Course
from user.decorators import teacher_required, creator_required


def do(request, task_id, course_id=None, slide_id=None):
    """
    Student form for answering/viewing a multiple choice task

    Parameters
    ----------
    request : Http request

    task_id : int
        ID of Task instance
    course_id : int
        ID of Course instance
    """

    context = setup_common_new_task_context(task_id, slide_id, course_id)
    slide_cache.load_slide_to_cache(context['slide'].id)

    # ======== Multiple choice specific ========
    multiple_choice = context['task'].multiplechoice

    answered = []
    choice_text = []
    if request.method == 'POST':
        # Process form
        id_post_choice = request.POST.getlist('choice', None)
        if id_post_choice:
            for id in id_post_choice:
                choice = Choice.objects.get(task=multiple_choice, id=id)
                choice_text.append(choice.text)
                if choice.correct:
                    answered.append('correct')
                else:
                    answered.append('incorrect')
        else:
            answered.append('no')

    # Determine if question is single or multiple choice
    counter_corr_answ = len(list(Choice.objects.filter(task=multiple_choice, correct=True)))

    context['multiple_choice'] = multiple_choice
    context['answered'] = answered
    context['len_answered'] = len(answered)
    context['choice_text'] = choice_text
    context['counter_corr_answ'] = counter_corr_answ
    return render(request, 'multiple_choice/do.html', context)


@teacher_required
def new(request, slide_id, course_id=None):
    """
    Teacher form for creating a multiple choice task

    Parameters
    ----------
    request : Http request

    slide_id : int
        ID of Slide instance
    course_id : int
        ID of Course instance
    """

    # Get slide
    slide = slide_cache.load_slide_to_cache(slide_id)

    # Process forms
    ChoiceFormset = formset_factory(ChoiceForm, extra=5)
    if request.method == 'POST':  # Form was submitted
        task_form = TaskForm(request.POST)
        multiple_choice_form = MultipleChoiceForm(request.POST)
        choice_formset = ChoiceFormset(request.POST)

        with transaction.atomic():  # Make save operation atomic
            if multiple_choice_form.is_valid() and task_form.is_valid() and choice_formset.is_valid():

                task = process_new_task_request(request, slide_id, course_id)

                # Create multiple choice
                multiple_choice = multiple_choice_form.save(commit=False)
                multiple_choice.task = task
                multiple_choice.save()

                # Create choices
                for choiceForm in choice_formset:
                    choice = choiceForm.save(commit=False)
                    if len(choice.text) > 0:
                        choice.task = multiple_choice
                        choice.save()

                # Give a message back to the user
                messages.add_message(request, messages.SUCCESS, 'Task added successfully!')
                if course_id is not None and course_id in Course.objects.values_list('id', flat=True):
                    return redirect('course:view', course_id=course_id, active_tab='tasks')
                return redirect('task:list')
    else:
        task_form = TaskForm()
        multiple_choice_form = MultipleChoiceForm()
        choice_formset = ChoiceFormset()

    return render(request, 'multiple_choice/new.html', {
        'slide': slide,
        'taskForm': task_form,
        'multipleChoiceForm': multiple_choice_form,
        'choiceFormset': choice_formset,
    })


@creator_required
@teacher_required
def edit(request, task_id, course_id=None):
    """
    Teacher form for editing a multiple choice task

        Parameters
    ----------
    request : Http request

    task_id : int
        ID of Task instance
    course_id : int
        ID of Course instance
    """

    context = setup_common_edit_task_context(task_id, course_id)

    ChoiceFormset = modelformset_factory(Choice, form=ChoiceForm, extra=4, max_num=4)
    multiple_choice = get_object_or_404(MultipleChoice, task=context['task'])
    choices = Choice.objects.filter(task=multiple_choice)

    # Process forms
    if request.method == 'POST':  # Form was submitted

        task_form = TaskForm(request.POST or None, instance=context['task'])
        multiple_choice_form = MultipleChoiceForm(request.POST or None, instance=multiple_choice)
        choice_formset = ChoiceFormset(request.POST)

        with transaction.atomic():  # Make save operation atomic
            if task_form.is_valid() and multiple_choice_form.is_valid():

                # Save instance data to database
                task = task_form.save()
                process_edit_task_request(request, task, task_form)
                multiple_choice = multiple_choice_form.save()
                Choice.objects.filter(task=multiple_choice).delete()

                for choiceForm in choice_formset:
                    choice = Choice()
                    text = request.POST.get(f"{choiceForm.prefix}-text")
                    correct = request.POST.get(f"{choiceForm.prefix}-correct")

                    if len(text) > 0:
                        choice.task = multiple_choice
                        choice.text = text
                        if correct:
                            choice.correct = True
                        else:
                            choice.correct = False
                        choice.save()

                messages.add_message(request, messages.SUCCESS,
                                     f'The task {task.name} was altered!')

                if course_id is not None and course_id in Course.objects.values_list('id', flat=True):
                    return redirect('course:view', course_id=course_id, active_tab='tasks')

        return redirect('task:list')


    else:

        task_form = TaskForm(instance=context['task'])

        task_form.fields['other_tags'].initial = context['task'].tags.filter(is_stain=False, is_organ=False)

        try:

            task_form.fields['organ_tags'].initial = context['task'].tags.get(is_organ=True)

        except:

            pass
        multiple_choice_form = MultipleChoiceForm(instance=context['task'].multiplechoice)
        choice_formset = ChoiceFormset(queryset=choices)

        context['taskForm'] = task_form
        context['multipleChoiceForm'] = multiple_choice_form
        context['choiceFormset'] = choice_formset

        slide_cache.load_slide_to_cache(context['slide'].id)
        return render(request, 'multiple_choice/new.html', context)


def get_choice_formset():
    ChoiceFormset = formset_factory(ChoiceForm, extra=4)
    choice_formset = ChoiceFormset()
    return choice_formset

multiple_choice/templates/multiple_choice/do.html
{% extends "task/do_task_two_column.html" %}


{% block task_instructions %}
{{ multiple_choice.instructions }}
{% endblock task_instructions %}

{% block task_question %}
{{ multiple_choice.question }}
{% endblock task_question %}

{% block content_left %}

<form action="{% url 'multiple_choice:do' task_id=task.id course_id=course_id slide_id=slide_id %}" method="post">
    {% csrf_token %}
    {% for choice in multiple_choice.choice_set.all %}
        {% if counter_corr_answ <= 1 %}
            {% if choice.text in choice_text %}
                <input class="form-check-input" type="radio" checked name="choice" value="{{ choice.id }}">
            {% else %}
                <input class="form-check-input" type="radio" name="choice" value="{{ choice.id }}">
            {% endif %}
        {% else %}
            {% if choice.text in choice_text %}
                <input class="form-check-input" type="checkbox" checked name="choice" value="{{ choice.id }}">
            {% else %}
                <input class="form-check-input" type="checkbox" name="choice" value="{{ choice.id }}">
            {% endif %}
        {% endif %}

        <span
            {% if answered %}
                {% if not 'no' in answered %}
                    {% if choice.correct %}
                        style="color: green"
                    {% else %}
                        style="color: red"
                    {% endif %}
                {% endif %}
            {% endif %}>
            {{ choice.text }}
            {% if answered and not 'no' in answered %}
                {% if choice.correct %}
                    &#10004;    {# check mark #}
                {% else %}
                    &#10006;    {# cross/X #}
                {% endif %}
            {% endif %}
        </span><br>
    {% endfor %}

    <div style="margin-top: 10px;">
        <input class="LPButton" type="submit" value="Submit">

        {% if answered and 'no' not in answered %}
            <div class="LPButton" style="margin-top: 0;">
                <a href="{% url next_task.do_url task_id=next_task.id course_id=course_id slide_id=slide_id %}">Next Task</a>
            </div>
        {% endif %}

    </div>
</form>

{% if answered %}
    {% if 'no' in answered %}
        <a style="color: darkslateblue; font-size: large; font-weight: bold">Please make a choice!</a>
    {% else %}
        {% if 'incorrect' in answered %}
            <a style="color: red; font-size: large; font-weight: bold">Wrong!</a>
        {% else %}
            {% if len_answered == counter_corr_answ %}
                <a style="color: green; font-size: large; font-weight: bold">Correct!</a>
            {% else %}
                <a style="color: darkorange; font-size: large; font-weight: bold">You are missing some answers!</a>
            {% endif %}
        {% endif %}

        {% if multiple_choice.explanation %}
            <div class="card mx-auto mt-4 border-success">
                <div class="card-tile">Explanation of answer</div>
                <div class="card-body">{{ multiple_choice.explanation }}</div>
            </div>
        {% endif %}

    {% endif %}
{% endif %}

{% endblock content_left %}

multiple_choice/templates/multiple_choice/edit_mc.html
{% extends 'learnpathology/base.html' %}

{% block content %}

<div class="container">
<h1>Edit multiple choice</h1>
</div>

<div class="card mx-auto text-center" style="width: 90%">
<div class="card-body">
<div class="card-text">

<p>
    Update the information you wish to update, then click the
    <i>Update multiple choice</i> button
</p>

<form method="post">
    {% csrf_token %}
    {{ taskForm.management_form }}
    <table class="table">

        <thead class="thead-light">
            <tr><th colspan="2">Multiple choice info</th></tr>
        </thead>
        <tr>
            <th>{{ taskForm.name.label }} (short, decriptive)</th>
            <td>{{ taskForm.name }}</td>
        </tr>
        <tr>
            <th>{{ multipleChoiceForm.question.label }}</th>
            <td>{{ multipleChoiceForm.question }}</td>
        </tr>
        <tr>
            <th>{{ multipleChoiceForm.instructions.label }}</th>
            <td>{{ multipleChoiceForm.instructions }}</td>
        </tr>


        <thead class="thead-light">
            <tr><th colspan="2">Answer alternatives (check box if alternative is correct)</th></tr>
        </thead>
        {{ choiceFormset.management_form }}
        {% for choiceForm in choiceFormset %}
            {{ choiceForm.id }} <!-- Need to explicitly render form id when not iterating through all fields -->
            <tr>
                <td>{{ "Option" }}</td>
                <td>{{ choiceForm.text }} {{ choiceForm.correct }}</td>
            </tr>
        {% endfor %}


        <thead class="thead-light">
            <tr><th colspan="2">Task metadata and tagging</th></tr>
        </thead>
        <tr>
            <th>{{ taskForm.pathology.label }}</th>
            <td>{{ taskForm.pathology }}</td>
        </tr>
        <tr>
            <th>{{ taskForm.organ_tags.label }}</th>
            <td>{{ taskForm.organ_tags }}</td>
        </tr>
        <tr>
            <th>{{ taskForm.other_tags.label }}</th>
            <td>{{ taskForm.other_tags }}</td>
        </tr>

        <thead class="thead-light">
            <tr><th colspan="2">Annotate WSI</th></tr>
        </thead>
        <tr><td colspan="2">
            {% include 'slide/view_wsi_and_edit_annotations.html' with slide=slide pointers=pointers %}

            <br>
            <input type="submit" value="Update multiple choice">
        </td></tr>
    </table>

</form>


</div>
</div>
</div>
{% endblock content %}

multiple_choice/templates/multiple_choice/new.html
{% extends 'task/new_or_edit_step2_add_info_and_annotate.html' %}


{% block task_type %}
Multiple choice
{% endblock task_type %}


{% block task_type_new_url %}
{{ new_url }}
{% endblock task_type_new_url %}


{% block specific_task_type_form %}

{# The tag <form class="form" method="post"> is in 'task/new_or_edit_step2_add_info_and_annotate.html' #}
<table class="table">

    <thead class="thead-light">
        <tr><th colspan="2">Multiple choice info</th></tr>
    </thead>
    <tr>
        <th>{{ taskForm.name.label }} (short, descriptive)</th>
        <td>{{ taskForm.name }}</td>
    </tr>
    <tr>
        <th>{{ multipleChoiceForm.question.label }}</th>
        <td>{{ multipleChoiceForm.question }}</td>
    </tr>
    <tr>
        <th>{{ multipleChoiceForm.instructions.label }}</th>
        <td>{{ multipleChoiceForm.instructions }}</td>
    </tr>


    <thead class="thead-light">
        <tr><th colspan="2">Answer alternatives (check box if alternative is correct)</th></tr>
    </thead>
    {{ choiceFormset.management_form }}
    {% for choiceForm in choiceFormset %}
        {{ choiceForm.id }} <!-- Need to explicitly render form id when not iterating through all fields -->
        <tr>
            <td>{{ "Option" }}</td>
            <td>{{ choiceForm.text }} {{ choiceForm.correct }}</td>
        </tr>
    {% endfor %}

    <thead class="thead-light">
        <tr><th colspan="2">Explanation of answer</th></tr>
    </thead>
    <tr>
        <th>{{ multipleChoiceForm.explanation.label }} (optional)</th>
        <td>{{ multipleChoiceForm.explanation }}</td>
    </tr>

</table>

{% endblock specific_task_type_form %}