course/urls.py
from django.urls import path, include
from course import views

app_name = 'course'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('edit/<int:course_id>', views.edit, name='edit'),
    path('edit_description/<int:course_id>', views.edit_long_description, name='edit_description'),
    path('edit_learning_outcomes/<int:course_id>', views.edit_learning_outcomes, name='edit_learning_outcomes'),
    path('delete/<int:course_id>', views.delete, name='delete'),
    path('view/<int:course_id>', views.course_page, name='view'),
    path('view/<int:course_id>/<str:active_tab>', views.course_page, name='view'),
    path('view/<int:course_id>/<int:return_task>', views.course_page, name='view'),
    path('slide_selection/<int:course_id>', views.slide_selection, name='slide_selection'),
    path('slide_selection/<int:course_id>/reset', views.reset_slide_selection, name='reset_slide_selection'),
    path('task_selection/<int:course_id>', views.task_selection, name='task_selection'),
    path('add_item/', views.add_to_course, name='add_item'),
    path('remove_item/', views.remove_from_course, name='remove_item'),
  path('<int:course_id>/upload/', views.upload_material, name='upload_material'),
]

free_text/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from free_text import views

app_name = 'free_text'
urlpatterns = [
    path('do/<int:task_id>/<int:course_id>/<int:slide_id>', views.do, name='do'),
    path('new/<int:slide_id>/', views.new, name='new'),
    path('new/<int:slide_id>/<int:course_id>', views.new, name='new'),
    path('edit/<int:task_id>/<int:course_id>', views.edit, name='edit'),
    path('edit/<int:task_id>/', views.edit, name='edit'),

]

learnpathology/urls.py
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

import learnpathology.views
import slide.views

urlpatterns = [
    path('', learnpathology.views.index, name='frontpage'),
    path('privacy/', learnpathology.views.privacy_info, name='privacy'),
    path('viewer/<int:slide_id>/', slide.views.whole_slide_viewer, name="view_wsi"),
    path('viewer/tile/<int:slide_id>/<int:osd_level>/<int:x>/<int:y>/', slide.views.tile, name="tile"),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('multiple_choice/', include('multiple_choice.urls')),
    path('slide/', include('slide.urls')),
    path('tag/', include('tag.urls')),
    path('course/', include('course.urls')),
    path('task/', include('task.urls')),
    path('comparison/', include('comparison.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('free_text/', include('free_text.urls')),
    path('click_question/', include('click_question.urls')),
    path('one_to_one/', include('one_to_one.urls')),
    path('annotation_task/', include('annotation_task.urls')),

    path('one_column/', learnpathology.views.test_one_column),
    path('two_column/', learnpathology.views.test_two_column),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_FEIDE_LOGIN:
    urlpatterns += [path('accounts/', include('feide.urls')),]
    #urlpatterns += [path('accounts/', include('allauth.urls')),]

urlpatterns += [
    # Define specific paths (can be used with {% url %} tag
    # path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    # path('privacy/', views.flatpage, {'url': '/privacy/'}, name='privacy'),

    # Or, use this 'catchall' pattern for all flatpages
    re_path(r'^(?P<url>.*/)$', views.flatpage),
]

one_to_one/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from one_to_one import views

app_name = 'one_to_one'
urlpatterns = [
    path('do/<int:task_id>/<int:course_id>/<int:slide_id>', views.do, name='do'),
    path('new/<int:slide_id>/', views.new, name='new'),
    path('new/<int:slide_id>/<int:course_id>', views.new, name='new'),
    path('edit/<int:task_id>/', views.edit, name='edit'),
    path('edit/<int:task_id>/<int:course_id>', views.edit, name='edit'),

]

slide/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
import os
from learnpathology import settings
from slide import views

app_name = 'slide'
urlpatterns = [
    path('list/', views.index, name='list'),
    path('browser/', views.image_browser, name='browser'),
    path('browser/reset', views.reset_image_browser, name='browser_reset'),
    #path('browser/grid-view', views.grid_view, name='grid_view'),
    #path('browser/list-view', views.list_view, name='list_view'),
    path('view/<int:slide_id>/', views.whole_slide_view_full, name='view_full'),
    path('view/<int:slide_id>/<int:course_id>', views.whole_slide_view_full, name='view_full'),
    path('edit-tags/<int:slide_id>', views.edit_general_pathology_tags, name='edit_tags'),
    path('add-tag/', views.add_tag, name='add_tag'),
    path('remove-tag/', views.remove_tag, name='remove_tag'),
    # Annotation stuff
    path('annotation/create/', views.create_annotation, name='create_annotation'),
    path('annotation/update/', views.update_annotation, name='update_annotation'),
    path('annotation/delete/', views.delete_annotation, name='delete_annotation'),
    path('upload/', views.upload_slides, name='upload_slides'),
    path('upload/process/', views.process_uploaded_slides, name='process_uploads'),
    path('upload/view/', views.view_uploaded_slides, name='view_uploads'),
    path('edit/<int:slide_id>', views.edit_slide_metadata, name='edit_metadata'),
] + static('thumbnails/', document_root=settings.SLIDE_THUMBNAILS_DIR) \
  + static('uploads/thumbnails/', document_root=os.path.join(settings.TEMP_UPLOADED_SLIDE_DIR, 'thumbnails'))

tag/urls.py
from django.urls import path, include
from tag import views

app_name = 'tag'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('edit/<int:tag_id>/', views.edit, name='edit'),
    path('delete/<int:tag_id>/', views.delete, name='delete'),
]

task/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from task import views

app_name = 'task'
urlpatterns = [
    path('new1/', views.new1, name='new1'),
    path('new1/<int:course_id>', views.new1, name='new1'),
    path('new2/', views.new2, name='new2'),
    path('new2/<str:course_id>', views.new2, name='new2'),
    path('new3/<int:course_id>', views.new3, name='new3'),
    path('new3/', views.new3, name='new3'),
    path('list/', views.list, name='list'),
    path('list/<int:slide_id>', views.list, name='list'),
    path('delete/<int:task_id>/', views.delete, name='task_delete'),
    path('reset', views.reset_image_browser, name='reset'),
    path('reset/<int:course_id>', views.reset_image_browser, name='reset'),
]

task/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

from course.models import Course
from slide.models import Slide
from slide.views import *
from user.decorators import teacher_required, creator_required
from task.models import Task
from tag.models import Tag

from task.forms import TaskForm
from multiple_choice.forms import MultipleChoiceForm
from multiple_choice.views import get_choice_formset
from free_text.forms import FreeTextForm
from click_question.forms import ClickQuestionForm
from one_to_one.forms import OneToOneForm
from one_to_one.views import get_sorting_pair_formset
from annotation_task.views import AnnotationTaskForm


def list(request, slide_id=None):
    """
    Show list of tasks
    """


    if slide_id:
        tasks = Task.objects.filter(annotated_slide__slide=slide_id)
    else:
        tasks = Task.objects.all()
        slide_id = 0



    # Filters
    organs = request.GET.getlist('organ[]')
    if len(organs) > 0:
        tasks = tasks.filter(tags__in=organs)
    stains = request.GET.getlist('stain[]')
    if len(stains) > 0:
        tasks = tasks.filter(tags__in=stains)
    tags = request.GET.getlist('tag[]')
    if len(tags) > 0:
        tasks = tasks.filter(tags__in=tags).distinct()

    selected_pathology = request.GET.get('pathology', False)
    selected_histology = request.GET.get('histology', False)
    if not selected_pathology and not selected_histology:
        selected_pathology = True
        selected_histology = True
    if selected_pathology and not selected_histology:
        tasks = tasks.filter(pathology=True)
    elif not selected_pathology and selected_histology:
        tasks = tasks.filter(pathology=False)

    return render(request, "task/list.html", {
        'tasks': tasks.order_by('-id'),
        'organ_tags': Tag.objects.filter(is_organ=True),
        'stain_tags': Tag.objects.filter(is_stain=True),
        'other_tags': Tag.objects.filter(is_stain=False, is_organ=False),
        'selected_organ_tags': organs,
        'selected_stain_tags': stains,
        'selected_other_tags': tags,
        'selected_pathology': selected_pathology,
        'selected_histology': selected_histology,
        'slide_id': slide_id,
    })

@teacher_required
def new1(request, course_id=None):
    context = {}

    if course_id:
        context['course_id']= course_id

    return render(request, 'task/new_or_edit_select_type.html', context)

@teacher_required
def new3(request, course_id=None):
    context = {}
    context['course_id'] = course_id
    return render(request, 'task/new_or_edit_step2_add_info_and_annotate.html', context)

@teacher_required
def new2(request, course_id=None):
    last_url = request.headers.get('referer', '')
    prev_context = {} if ('task/new2/' not in last_url) else request.session.get('image_browser_context',
                                                                                              {})
    request.session['image_browser_context'] = {}
    context = {}
    if 'task_type' in request.GET:
        # If task_type is present in the GET request, use it
        task_type = request.GET.get('task_type')

        # Store task_type in session to persist across requests
        request.session['task_type'] = task_type
        context['task_type'] = task_type
        if course_id:
            request.session['course_id'] = course_id
        else :
            request.session['course_id'] = None
    else:
        # If this is not the first request, retrieve task_type from session
        context['task_type'] = request.session.get('task_type', None)
        course_id = request.session.get('course_id', None)


    # ==================================================================
    # Set up variables for which filtering options have been applied
    # ==================================================================
    organ_changed = ('organ-system' in request.GET)  # Organ selection changed
    general_path_changed = ('general_pathology_button' in request.GET)  # General pathology changed
    hist_path_changed = ('histology-pathology' in request.GET)  # Histology/pathology changed
    search_button_clicked = ('submit_button' in request.GET)  # Search query entered
    clear_search_clicked = ('clear_button' in request.GET)  # Search cleared

    # ==================================================================
    # Find selections for filtering options
    # ==================================================================
    # ORGAN FILTER
    if organ_changed:
        # Update the organ selection from the GET request
        selected_organ_tag_id = [request.GET.get('organ-system')]
    else:
        # Retrieve the previous organ selection or set to 'all'
        selected_organ_tag_id = prev_context['selected_organ_tag_ids'] if (
                'selected_organ_tag_ids' in prev_context) else ['all']
    if 'all' in selected_organ_tag_id:
        organ_tags = Tag.objects.filter(is_organ=True)
    else:
        organ_tags = Tag.objects.filter(is_organ=True, id__in=selected_organ_tag_id)

    # HISTOLOGY/PATHOLOGY FILTER
    if hist_path_changed:
        # Update the histology_pathology variable from the GET request
        histology_pathology = request.GET.get('histology-pathology')

        selected_histology = (histology_pathology == 'histology')
        selected_pathology = (histology_pathology == 'pathology')
    else:
        # Retrieve the previous values or set to False
        selected_histology = prev_context['selected_histology'] if 'selected_histology' in prev_context else False
        selected_pathology = prev_context['selected_pathology'] if 'selected_pathology' in prev_context else False

    selected_both = (not selected_histology and not selected_pathology)

    # SEARCH FILTER
    if search_button_clicked:
        search_query = request.GET.get('search')
        if len(search_query) == 0:
            search_query = None
    elif clear_search_clicked:
        search_query = None
    else:
        try:
            search_query = prev_context['search_query']
        except KeyError as err:
            search_query = None

    # ==================================================================
    # Filter slides, and apply search if the search button was clicked
    # ==================================================================
    if course_id :
        slides = Slide.objects.filter(course=course_id)
        context['course_id'] = course_id
    else:
        slides = Slide.objects.all()
    slides = slides.filter(tags__in=organ_tags)
    if not selected_both:
        slides = slides.filter(pathology=selected_pathology)
    if not (hist_path_changed and 'selected_general_pathology_ids' in prev_context):
        gen_path_tag_id = None
        if search_button_clicked and 'selected_general_pathology_ids' in prev_context:
            gen_path_tag_id = prev_context['selected_general_pathology_ids'][0]
        elif general_path_changed:
            gen_path_tag_id = int(request.GET.get('general_pathology_button').split('-')[-1])
        if gen_path_tag_id is not None:
            gen_path_tag = Tag.objects.get(id=gen_path_tag_id)
            slides = slides.filter(tags__in=[gen_path_tag])
            context['selected_general_pathology'] = gen_path_tag
            request.session['image_browser_context']['selected_general_pathology_ids'] = queryset_to_id_list(
                Tag.objects.filter(id=gen_path_tag_id))  # function takes queryset
    if search_query is not None:  # If search was updated, search among applicable_slides
        slides = slides.filter(Q(name__contains=search_query) | Q(description__contains=search_query))

    # ==================================================================
    # Update context
    # ==================================================================


    context['slides'] = sorted(slides, key=lambda s: s.name)
    context['selected_organ_tag'] = ['all'] if 'all' in selected_organ_tag_id else Tag.objects.filter(
        id__in=selected_organ_tag_id)
    context['selected_both'] = selected_both
    context['selected_histology'] = selected_histology
    context['selected_pathology'] = selected_pathology
    context['search_query'] = search_query
    context['organ_tags'] = Tag.objects.filter(is_organ=True).order_by('name')
    general_pathology_tags = [tag for tag in Tag.objects.filter(is_organ=False, is_stain=False) if
                              tag.name.lower() in GENERAL_PATHOLOGY_TAGS]
    context['general_pathology_tags'] = sorted(general_pathology_tags, key=lambda tag: tag.name)

    for key, val in prev_context.items():
        if key not in context and key not in ('selected_organ_tag_ids', 'selected_general_pathology_ids'):
            context[key] = prev_context[key]

    # ==================================================================
    # Update session variable to store selection
    # ==================================================================
    keys_that_contain_querysets = (
        'slides', 'selected_organ_tag', 'organ_tags', 'general_pathology_tags', 'selected_general_pathology',
        'selected_general_pathology_ids')
    for key, val in context.items():
        if key not in request.session['image_browser_context'] and key not in keys_that_contain_querysets:
            request.session['image_browser_context'][key] = context[key]
    request.session['image_browser_context']['selected_organ_tag_ids'] = queryset_to_id_list(
        context['selected_organ_tag'])
    request.session.modified = True

    if request.POST:


        task_type = context['task_type']
        context = {}
        selected_slide_id = request.POST.get('selected_slide_id')
        slide = Slide.objects.get(pk=selected_slide_id)
        slide_cache.load_slide_to_cache(slide.id)

        context['slide'] = slide
        context['taskForm'] = TaskForm()


        if course_id is not None:
            context['course_id'] = course_id

task/templates/task/do_task_one_column.html
{#{% extends "task/do_task_common.html" %}#}
{% extends "learnpathology/single_content_layout.html" %}

{% load get_type %}


{% block page_title %}
{{ task|get_task_type_for_header }}{{ task.name }}
{% endblock page_title %}


{% block breadcrumb_items %}
    {% if course_id %}
        <li class="breadcrumb-item"><a href="{% url 'course:index' %}">Courses</a></li>
        <li class="breadcrumb-item"><a href="{% url 'course:view' course_id=course_id active_tab='tasks' %}">{{ course.title }}</a></li>
    {% else %}
        <li class="breadcrumb-item"><a href="{% url 'task:list' %}">Task list</a></li>
    {% endif %}
    <li class="breadcrumb-item">Task: {{ task.name }}</li>

{% endblock breadcrumb_items %}


{% block search_bar %}
{% endblock search_bar %}


{% block button_row %}
   {% if slide_id %}
<div class="custom-button" style="">
    <a href="{% url 'slide:view_full' slide_id%}" style="display: inline-flex;">
        <div class="button-icon">
            <span class="iconify" data-icon="fluent:arrow-circle-left-24-regular" data-width="24" data-height="24" style="font-weight: bolder;"></span>
        </div>
        <div style="justify-content: flex-start; align-items: center; display: flex">
            <div class="button-text">Return to slide</div>
        </div>
    </a>
</div>    {% endif %}

<div class="custom-button" style="">
    <a href="{% if course_id %}{% url 'course:view' course_id=course_id active_tab='tasks' %}{% else %}{% url 'task:list' slide_id=slide_id %}{% endif %}" style="display: inline-flex;">
        <div class="button-icon">
            <span class="iconify" data-icon="fluent:arrow-circle-left-24-regular" data-width="24" data-height="24" style="font-weight: bolder;"></span>
        </div>
        <div style="justify-content: flex-start; align-items: center; display: flex">
            <div class="button-text">Return to {% if course_id %}course{% else %}task list{% endif %}</div>
        </div>
    </a>
</div>
{% endblock button_row %}


{% block content %}

<div class="card w-100 mx-auto text-center" style="height: 85%; min-height: 600px;">
<div class="card-body" style="height: 100%">

    <div style="padding: 6px 24px 6px 24px;">
        <h3>
            {% block task_instructions %}
            {% endblock task_instructions %}
        </h3>
    </div>

    <h4 style="margin-top: 20px; margin-bottom: 20px;">
        {% block task_question %}
        {% endblock task_question %}
    </h4>

    {% block card_content_top %}
    {% endblock card_content_top %}

    {% block card_content_bottom %}
    {% if slide %}
        {% include 'slide/view_wsi_do_task.html' with two_column=0 slide=slide annotated_slide=task.annotated_slide %}
    {% else %}
        {% include 'slide/view_wsi_do_task.html' with slide=slide annotated_slide=task.annotated_slide %}
    {% endif %}
    {% endblock card_content_bottom %}
</div>
</div>


{% endblock content %}


{% block task_javascript %}
{% endblock task_javascript %}

task/templates/task/do_task_two_column.html
{#{% extends "task/do_task_common.html" %}#}
{% extends "learnpathology/two_column_layout.html" %}

{% load get_type %}
{% load slide_filters %}


{% block page_title %}
{{ task|get_task_type_for_header }}{{ task.name }}
{% endblock page_title %}


{% block breadcrumb_items %}
    {% if course_id %}
        <li class="breadcrumb-item"><a href="{% url 'course:index' %}">Courses</a></li>
        <li class="breadcrumb-item"><a href="{% url 'course:view' course_id=course_id active_tab='tasks' %}">{{ course.title }}</a></li>
    {% else %}
        <li class="breadcrumb-item"><a href="{% url 'task:list' %}">Task list</a></li>
    {% endif %}
    <li class="breadcrumb-item">Task: {{ task.name }}</li>

{% endblock breadcrumb_items %}


{% block search_bar %}
{% endblock search_bar %}


{% block button_row %}
       {% if slide_id %}
<div class="custom-button" style="">
    <a href="{% url 'slide:view_full' slide_id%}" style="display: inline-flex;">
        <div class="button-icon">
            <span class="iconify" data-icon="fluent:arrow-circle-left-24-regular" data-width="24" data-height="24" style="font-weight: bolder;"></span>
        </div>
        <div style="justify-content: flex-start; align-items: center; display: flex">
            <div class="button-text">Return to slide</div>
        </div>
    </a>
</div>    {% endif %}

<div class="custom-button" style="">
    <a href="{% if course_id %}{% url 'course:view' course_id=course_id active_tab='tasks' %}{% else %}{% url 'task:list' slide_id=slide_id %}{% endif %}" style="display: inline-flex;">
        <div class="button-icon">
            <span class="iconify" data-icon="fluent:arrow-circle-left-24-regular" data-width="24" data-height="24" style="font-weight: bolder;"></span>
        </div>
        <div style="justify-content: flex-start; align-items: center; display: flex">
            <div class="button-text">Return to {% if course_id %}course{% else %}task list{% endif %}</div>
        </div>
    </a>
</div>
{% endblock button_row %}


{% block content %}

<div class="card w-100 mx-auto text-center" style="height: 85%; min-height: 600px;">
<div class="card-body" style="height: 100%">

    <div class="row h-100">
        <div class="col-6">
            <div id="contentLeft" style="width: 100%;">
                <div style="padding: 6px 24px 6px 24px;">
                    <h3>
                        {% block task_instructions %}
                        {% endblock task_instructions %}
                    </h3>
                </div>

                <h4 style="margin-top: 20px; margin-bottom: 20px;">
                    {% block task_question %}
                    {% endblock task_question %}
                </h4>
                {% block content_left %}
                {% endblock content_left %}
            </div>
        </div>
        <div class="col-6" style="height: 100%;">
            <div id="contentRight" style="width: 100%; height: 100%;">
                {% if slide %}
                    {% include 'slide/view_wsi_do_task.html' with two_column=1 slide=slide annotated_slide=task.annotated_slide %}
                {% else %}
                    {% include 'slide/view_wsi_do_task.html' with slide=slide annotated_slide=task.annotated_slide %}
                {% endif %}
                {% block content_right %}
                {% endblock content_right %}
            </div>
        </div>
    </div>
</div>
</div>



{% endblock content %}


{% block task_javascript %}
{% endblock task_javascript %}

task/templates/task/list.html
{% extends 'learnpathology/single_content_layout.html' %}
{% load to_class_name %}


{% block page_title %}
Task list
{% endblock page_title %}


{% block breadcrumb_items %}
{#    <li class="breadcrumb-item"><a href="{% url 'task:list' %}">Task list</a></li>#}
    <li class="breadcrumb-item">Task list</li>
{% endblock breadcrumb_items %}


<!-- Uncommenting the below block (two lines) will hide the search bar -->
{#{% block search_bar %}#}
{#{% endblock search_bar %}#}


{% block button_row %}
{% if slide_id %}
    <div class="custom-button" style="">
    <a href="{% url 'slide:view_full' slide_id=slide_id %}" style="display: inline-flex;">
        <div class="button-icon">
            <span class="iconify" data-icon="fluent:arrow-circle-left-24-regular" data-width="24" data-height="24" style="font-weight: bolder;"></span>
        </div>
        <div style="justify-content: flex-start; align-items: center; display: flex">
            <div class="button-text">Return to slide</div>
        </div>
    </a>
</div>{% endif %}


{% if user.is_superuser or user.is_teacher %}
    <div class="custom-button" style="">
        <!-- TODO: Update url to not include slide_id since slide is selected when making task -->
        <a href="{% url 'task:new1' %}" style="display: inline-flex;">
            <div class="button-icon">
                <span class="iconify" data-icon="fluent:add-24-regular" data-width="24" data-height="24" style="font-weight: bolder;"></span>
            </div>
            <div style="justify-content: flex-start; align-items: center; display: flex">
                <div class="button-text">New task</div>
            </div>
        </a>
    </div>
    {#<div class="custom-button" style="">#}
    {#    <!-- TODO: Update url to not include slide_id since slide is selected when making task -->#}
    {#    <a href="{% url 'multiple_choice:do_random' %}" style="display: inline-flex;">#}
    {#        <div class="button-icon">#}
    {#            <span class="iconify" data-icon="fluent:arrow-shuffle-24-regular" data-width="24" data-height="24" style="font-weight: bolder;"></span>#}
    {#        </div>#}
    {#        <div style="justify-content: flex-start; align-items: center; display: flex">#}
    {#            <div class="button-text">Random question</div>#}
    {#        </div>#}
    {#    </a>#}
    {#</div>#}
{% endif %}

{% endblock button_row %}



{% block content %}

    <div class="card mx-auto text-center" style="width: 100%">
        <div class="card-body">
            <div class="card-text">

                <div style="margin-bottom: 12px;">
                    <form class="form">
                        <b>Filter:</b>
                        Organ:
                        <select name="organ[]" multiple class="filter" style="width:20%">
                            {% for tag in organ_tags %}
                                <option value="{{ tag.id }}"{% if tag.id|slugify in selected_organ_tags %}selected="selected"{% endif %}>{{ tag.name }}</option>
                            {% endfor %}
                        </select>
                        Stain:
                        <select name="stain[]" multiple class="filter">
                            {% for tag in stain_tags %}
                                <option value="{{ tag.id }}"{% if tag.id|slugify in selected_stain_tags %}
                                        selected="selected"{% endif %}>{{ tag.name }}</option>
                            {% endfor %}
                        </select>
                        Pathology: <input type="checkbox" {% if selected_pathology %}checked="checked"{% endif %} name="pathology" onchange="this.form.submit();">
                        Histology: <input type="checkbox" {% if selected_histology %}checked="checked"{% endif %} name="histology" onchange="this.form.submit();">
                        Tag:
                        <select name="tag[]" multiple class="filter">
                            {% for tag in other_tags %}
                                <option value="{{ tag.id }}"{% if tag.id|slugify in selected_other_tags %} selected="selected"{% endif %}>{{ tag.name }}</option>
                            {% endfor %}
                        </select>
                    </form>
                </div>
                {% if tasks %}
                    <table class="table">
                        <thead class="thead-light">
                        <tr>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Attempt task</th>
                            {% if request.user.is_teacher or request.user.is_superuser %}
                                <th>Edit</th>
                                <th>Delete</th>
                            {% endif %}
                        </tr>
                        </thead>
                        {% for task in tasks %}
                            <tr>
                                <td><a href="{% url task.do_url task_id=task.id course_id=0 slide_id=slide_id%}">{{ task.name }}</a></td>
                                <td>{{ task.type }}</td>
                                <td><a href="{% url task.do_url task_id=task.id course_id=0 slide_id=slide_id %}">Do task</a></td>
                                {% if request.user.is_teacher or request.user.is_superuser %}
                                    <td><a href="{% url task.edit_url task.id %}" class="{% if user != task.created_by %}disabled-link{% endif %}">Edit</a></td>
                                    <td><a href="{% url 'task:task_delete' task.id %}" class="{% if user != task.created_by %}disabled-link{% endif %}">Delete</a></td>
                                {% endif %}
                            </tr>
                        {% endfor %}
                    </table>
                {% else %}
                    <p>
                        No tasks found with current filter.
                    </p>
                {% endif %}

            </div>
        </div>
    </div>
{% endblock content %}


{% block javascript %}

$(document).ready(function(){
    collapseSidebar();
});

{% endblock javascript %}

task/templates/task/new.html
{% extends 'learnpathology/single_content_layout.html' %}

{% load static %}


{% block breadcrumb_items %}
    {% if course_id %}
        <li class="breadcrumb-item"><a href="{% url 'course:index' %}">Courses</a></li>
        <li class="breadcrumb-item"><a href="#">"Course name"</a></li> <!-- TODO: Use course name -->
        {#        <li class="breadcrumb-item"><a href="#">{{ course.code }} - {{ course.name }}</a></li>#}
        <li class="breadcrumb-item">New task: {{ slide.name }}</li>
    {% else %}
        <li class="breadcrumb-item"><a href="{% url 'task:list' %}">Task list</a></li>
        <li class="breadcrumb-item">New task: {{ slide.name }}</li>
    {% endif %}

{% endblock breadcrumb_items %}


{% block search_bar %}
{% endblock search_bar %}


{% block button_row %}
<div class="custom-button" style="">
    {% if course_id %}
        <a href="{% url 'course:view' course_id=course_id %}" style="display: inline-flex;">
    {% else %}
        <a href="{% url 'task:list' %}" style="display: inline-flex;">
    {% endif %}
        <div class="button-icon">
            <span class="iconify" data-icon="fluent:bin-recycle-24-regular" data-width="24" data-height="24" style="font-weight: bolder;"></span>
        </div>
        <div style="justify-content: flex-start; align-items: center; display: flex">
            {% if task %}
                <div class="button-text">Cancel & Exit</div>
            {% else %}
                <div class="button-text">Exit & discard task</div>
            {% endif %}
        </div>
    </a>
</div>
{% endblock button_row %}


{% block content %}


{% endblock content %}


{% block javascript %}

$(document).ready(function(){
    collapseSidebar();
});

{% endblock javascript %}