course/urls.py
from django.urls import path, include
from course import views

app_name = 'course'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('edit/<int:course_id>', views.edit, name='edit'),
    path('edit_description/<int:course_id>', views.edit_long_description, name='edit_description'),
    path('edit_learning_outcomes/<int:course_id>', views.edit_learning_outcomes, name='edit_learning_outcomes'),
    path('delete/<int:course_id>', views.delete, name='delete'),
    path('view/<int:course_id>', views.course_page, name='view'),
    path('view/<int:course_id>/<str:active_tab>', views.course_page, name='view'),
    path('view/<int:course_id>/<int:return_task>', views.course_page, name='view'),
    path('slide_selection/<int:course_id>', views.slide_selection, name='slide_selection'),
    path('slide_selection/<int:course_id>/reset', views.reset_slide_selection, name='reset_slide_selection'),
    path('task_selection/<int:course_id>', views.task_selection, name='task_selection'),
    path('add_item/', views.add_to_course, name='add_item'),
    path('remove_item/', views.remove_from_course, name='remove_item'),
  path('<int:course_id>/upload/', views.upload_material, name='upload_material'),
]

learnpathology/urls.py
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

import learnpathology.views
import slide.views

urlpatterns = [
    path('', learnpathology.views.index, name='frontpage'),
    path('privacy/', learnpathology.views.privacy_info, name='privacy'),
    path('viewer/<int:slide_id>/', slide.views.whole_slide_viewer, name="view_wsi"),
    path('viewer/tile/<int:slide_id>/<int:osd_level>/<int:x>/<int:y>/', slide.views.tile, name="tile"),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('multiple_choice/', include('multiple_choice.urls')),
    path('slide/', include('slide.urls')),
    path('tag/', include('tag.urls')),
    path('course/', include('course.urls')),
    path('task/', include('task.urls')),
    path('comparison/', include('comparison.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('free_text/', include('free_text.urls')),
    path('click_question/', include('click_question.urls')),
    path('one_to_one/', include('one_to_one.urls')),
    path('annotation_task/', include('annotation_task.urls')),

    path('one_column/', learnpathology.views.test_one_column),
    path('two_column/', learnpathology.views.test_two_column),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_FEIDE_LOGIN:
    urlpatterns += [path('accounts/', include('feide.urls')),]
    #urlpatterns += [path('accounts/', include('allauth.urls')),]

urlpatterns += [
    # Define specific paths (can be used with {% url %} tag
    # path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    # path('privacy/', views.flatpage, {'url': '/privacy/'}, name='privacy'),

    # Or, use this 'catchall' pattern for all flatpages
    re_path(r'^(?P<url>.*/)$', views.flatpage),
]

tag/urls.py
from django.urls import path, include
from tag import views

app_name = 'tag'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('edit/<int:tag_id>/', views.edit, name='edit'),
    path('delete/<int:tag_id>/', views.delete, name='delete'),
]

task/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from task import views

app_name = 'task'
urlpatterns = [
    path('new1/', views.new1, name='new1'),
    path('new1/<int:course_id>', views.new1, name='new1'),
    path('new2/', views.new2, name='new2'),
    path('new2/<str:course_id>', views.new2, name='new2'),
    path('new3/<int:course_id>', views.new3, name='new3'),
    path('new3/', views.new3, name='new3'),
    path('list/', views.list, name='list'),
    path('list/<int:slide_id>', views.list, name='list'),
    path('delete/<int:task_id>/', views.delete, name='task_delete'),
    path('reset', views.reset_image_browser, name='reset'),
    path('reset/<int:course_id>', views.reset_image_browser, name='reset'),
]

course/models.py
import os.path

from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from slide.models import Slide
from task.models import Task
from user.models import User


class Course(models.Model):
    code = models.CharField(max_length=20)
    title = models.CharField(max_length=255)
    description = models.TextField()
    long_description = RichTextUploadingField(null=True, blank=True)  # longer description
    teacher = models.ManyToManyField(User)
    task = models.ManyToManyField(Task)
    slide = models.ManyToManyField(Slide)
    # TODO add annotations later
    learning_outcomes = RichTextField(null=True, blank=True, config_name='featherweight')

    def __str__(self):
        return self.code + " - " + self.title


class CourseMaterial(models.Model):
    """
    Model to store and access course materials (pdf, docx, pptx, mp4 files...)
    """
    name = models.CharField(max_length=255)
    path = models.CharField(max_length=1024)
    description = models.TextField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name} ({os.path.splitext(self.path)[-1]} file)'

course/forms.py
from django import forms
from django.forms import FileField, FileInput
from course.models import Course, CourseMaterial
from user.models import User


class CourseForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['teacher'].queryset = User.objects.filter(is_teacher=True).order_by('username')

    class Meta:
        model = Course
        fields = ['code', 'title', 'description', 'long_description', 'teacher']
        labels = {
            'code': 'Course code',
            'title': 'Course name',
            'description': 'Description (short, will be displayed in course list)',
            'long_description': 'Course description (visible on course page). You can also add this later.',
            'teacher': 'Teachers'
        }
        widgets = {
            'title': forms.Textarea(attrs={'rows': 1, 'cols': 100}),
            'description': forms.Textarea(attrs={'rows': 1, 'cols': 100}),
        }


class DeleteCourseForm(forms.Form):

    confirmDelete = forms.BooleanField(label="Yes, I want to delete the course",
                                       required=False)


class CourseLongDescriptionForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ['long_description']
        labels = {
            'long_description': 'Course description (visible on course page)'
        }


class CourseLearningOutcomesForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ['learning_outcomes']
        labels = {
            'learning_outcomes': 'Learning outcomes'
        }


class CourseMaterialForm(forms.ModelForm):

    file = FileField()
    class Meta:
        model = CourseMaterial
        fields = ['name', 'description', 'file']
        exclude = ['course', 'path']
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4, 'cols': 40}),
            'file': FileInput(),
        }

    def save(self, file_path='', **kwargs):
        # Update the created CourseMaterial object with the location of the uploaded file
        self.instance.path = file_path
        return super().save(**kwargs)

course/views.py
import os
import sys

from django.contrib import messages
from django.db import transaction
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core.files.uploadedfile import UploadedFile

from course.models import Course, CourseMaterial
from course.forms import CourseForm, DeleteCourseForm, \
    CourseLongDescriptionForm, CourseLearningOutcomesForm, CourseMaterialForm
from learnpathology.settings import MEDIA_ROOT
from slide.models import Slide
from slide.views import queryset_to_id_list, GENERAL_PATHOLOGY_TAGS
from tag.models import Tag
from task.models import Task

from user.decorators import teacher_required


def index(request):
    """
    Show index of available courses
    """

    courses = Course.objects.all()
    return render(request, "course/index.html",
                  {'courses': Course.objects.all().order_by('code')})


def course_page(request, course_id, return_task=None , active_tab=None):
    """
    Display a course page with course information and related slides and tasks
    """

    course = Course.objects.get(id=course_id)
    tasks = Task.objects.filter(course=course)
    slides = Slide.objects.filter(course=course)
    course_materials = CourseMaterial.objects.filter(course=course)


    return render(request, 'course/course_page.html', {
        'course': course,
        'tasks': tasks,
        'slides': slides,
        'course_materials': course_materials,
        'return_task': return_task,
        'active_tab': active_tab,
    })


@teacher_required
def new(request):
    """
    Teacher form for creating a course
    """

    if request.method == 'POST':  # Form was submitted
        courseForm = CourseForm(request.POST)
        if courseForm.is_valid():
            course = courseForm.save(commit=False)
            course.save()
            # Give a message back to the user
            messages.add_message(request, messages.SUCCESS, 'Course added successfully!')
            return redirect('course:view', course_id=course.id)
        else:
            # Render form with errors
            pass
    else:
        courseForm = CourseForm()

    return render(request, 'course/new.html', {'form': courseForm})


@teacher_required
def edit(request, course_id):
    """
    Teacher form for editing a course
    """

    course = get_object_or_404(Course, id=course_id)
    courseForm = CourseForm(request.POST or None, instance=course)

    if request.method == 'POST':  # Form was submitted
        if courseForm.is_valid():
            courseForm.save()
            messages.add_message(request, messages.SUCCESS,
                 f'The course {course.code} - {course.title} was altered!')
            return redirect('course:view', course_id=course_id, active_tab='course-description')

    return render(request, 'course/edit.html', {
        'form': courseForm,
        'course': course
    })


@teacher_required
def edit_long_description(request, course_id):
    """
    Teacher form for editing the course (long) description
    """

    course = get_object_or_404(Course, id=course_id)
    form = CourseLongDescriptionForm(request.POST or None, instance=course)

    if request.method == 'POST':  # Form was submitted
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                 f'The course {course.code} - {course.title} was altered!')
            return redirect('course:view', course_id=course_id)

    return render(request, 'course/edit_course_description.html', {
        'course': course,
        'form': form
    })


@teacher_required
def edit_learning_outcomes(request, course_id):
    """
    Teacher form for editing the course learning outcomes
    """

    course = get_object_or_404(Course, id=course_id)
    form = CourseLearningOutcomesForm(request.POST or None, instance=course)

    if request.method == 'POST':  # Form was submitted
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                 f'The course {course.code} - {course.title} was altered!')
            return redirect('course:view', course_id=course_id, active_tab='learning-outcomes')

    return render(request, 'course/edit_learning_outcomes.html', {
        'course': course,
        'form': form
    })


@teacher_required
def delete(request, course_id):
    """
    View to delete a course from the course database
    """

    if request.method == 'POST':  # Form was submitted
        form = DeleteCourseForm(request.POST)

        if form.is_valid():
            course = Course.objects.get(id=course_id)
            txt = f"{course.code} - {course.title}"

            if form.cleaned_data['confirmDelete']:
                course.delete()
                messages.add_message(request, messages.SUCCESS, f'The course {txt} was deleted')
            else:
                messages.add_message(request, messages.SUCCESS, f'The course {txt} was not deleted')

            return redirect('course:index')

    else:  # GET method
        # Render page with course info and "Delete? Yes/No"
        if course_id in Course.objects.all().values_list('id', flat=True):
            course = Course.objects.get(id=course_id)
            return render(request, 'course/delete.html',
                          {'form': DeleteCourseForm(), 'course': course})

        else:  # In case user enters invalid URL directly
            messages.add_message(request, messages.WARNING, 'Did not find course')
            return redirect('course:index')

    return redirect('course:index')





@teacher_required
def slide_selection(request, course_id):
    """
    Teacher form for adding slide(s) to a course
    """

    last_url = request.headers.get('referer', '')
    prev_context = {} if ('course/slide_selection/' not in last_url) else request.session.get('image_browser_context', {})
    request.session['image_browser_context'] = {}
    # Initialize empty context dictionary
    context = {}

    # ==================================================================
    # Set up variables for which filtering options have been applied
    # ==================================================================
    organ_changed = ('organ-system' in request.GET)                     # Organ selection changed
    general_path_changed = ('general_pathology_button' in request.GET)  # General pathology changed
    hist_path_changed = ('histology-pathology' in request.GET)          # Histology/pathology changed
    search_button_clicked = ('submit_button' in request.GET)            # Search query entered
    clear_search_clicked = ('clear_button' in request.GET)              # Search cleared

    # ==================================================================
    # Find selections for filtering options
    # ==================================================================
    # ORGAN FILTER
    if organ_changed:
        # Update the organ selection from the GET request
        selected_organ_tag_id = [request.GET.get('organ-system')]
    else:
        # Retrieve the previous organ selection or set to 'all'
        selected_organ_tag_id = prev_context['selected_organ_tag_ids'] if ('selected_organ_tag_ids' in prev_context) else ['all']
    if 'all' in selected_organ_tag_id:
        organ_tags = Tag.objects.filter(is_organ=True)
    else:
        organ_tags = Tag.objects.filter(is_organ=True, id__in=selected_organ_tag_id)

    # HISTOLOGY/PATHOLOGY FILTER
    if hist_path_changed:
        # Update the histology_pathology variable from the GET request
        histology_pathology = request.GET.get('histology-pathology')

        selected_histology = (histology_pathology == 'histology')
        selected_pathology = (histology_pathology == 'pathology')
    else:
        # Retrieve the previous values or set to False
        selected_histology = prev_context['selected_histology'] if 'selected_histology' in prev_context else False
        selected_pathology = prev_context['selected_pathology'] if 'selected_pathology' in prev_context else False

    selected_both = (not selected_histology and not selected_pathology)

    # SEARCH FILTER
    if search_button_clicked:
        search_query = request.GET.get('search')
        if len(search_query) == 0:
            search_query = None
    elif clear_search_clicked:
        search_query = None
    else:
        try:
            search_query = prev_context['search_query']
        except KeyError as err:
            search_query = None

    # ==================================================================
    # Filter slides, and apply search if the search button was clicked
    # ==================================================================
    slides = Slide.objects.all()
    slides = slides.filter(tags__in=organ_tags)
    if not selected_both:
        slides = slides.filter(pathology=selected_pathology)
    if not (hist_path_changed and 'selected_general_pathology_ids' in prev_context):
        gen_path_tag_id = None
        if search_button_clicked and 'selected_general_pathology_ids' in prev_context:
            gen_path_tag_id = prev_context['selected_general_pathology_ids'][0]
        elif general_path_changed:
            gen_path_tag_id = int(request.GET.get('general_pathology_button').split('-')[-1])
        if gen_path_tag_id is not None:
            gen_path_tag = Tag.objects.get(id=gen_path_tag_id)
            slides = slides.filter(tags__in=[gen_path_tag])
            context['selected_general_pathology'] = gen_path_tag
            request.session['image_browser_context']['selected_general_pathology_ids'] = queryset_to_id_list(Tag.objects.filter(id=gen_path_tag_id))  # function takes queryset
    if search_query is not None:    # If search was updated, search among applicable_slides
        slides = slides.filter(Q(name__contains=search_query) | Q(description__contains=search_query))

course/templates/course/course_page_content/course_description.html
{% block courseTabContent %}
{# This content is displayed within a containing <div class="card">...</div> #}

    <div class="card-body">
        {% if course.long_description %}

            <div class="card-text" style="text-align: left;">
                {% if request.user.is_teacher or request.user.is_superuser %}
                <div class="LPButton">
                    <a href="{% url 'course:edit_description' course.id  %}">Edit course description</a>
                </div>
                <br>
                {% endif %}
                <div class="card border-0">
                <div class="card-body"><div class="card-text">
                    {{ course.long_description | safe }}
                </div></div>
                </div>
            </div>

        {% else %}

            <div class="card-text" style="text-align: left">
                This course lacks a course description.
                {% if request.user.is_teacher or request.user.is_superuser %}
                You can add one now!
                <br>
                <div class="LPButton">
                    <a href="{% url 'course:edit_description' course.id  %}">Add course description</a>
                </div>
                {% endif %}
            </div>

        {% endif %}
    </div>

{% endblock courseTabContent %}

course/templates/course/course_page_content/course_materials.html
{% block courseTabContent %}
    {# This content is displayed within a containing <div class="card">...</div> #}

    <div class="card-body">
        <div class="card-text" style="text-align: left">

            {% if course_materials %}

                {% if request.user.is_teacher or request.user.is_superuser %}
                    <div class="LPButton">
                        <a href="{% url 'course:upload_material' course_id=course.id %}">Upload course materials</a>
                    </div>
                    <br>
                {% endif %}
                <div class="card border-0">
                    <div class="row">
                        <div class="col">
                            <div class="card-body">
                                <div class="card-text">

                                    Here are course materials
                                    <ul>
                                        {% for item in course_materials %}
                                            <li><a href="{{ item.path }}" download>
                                                {{ item.name }}
                                            </a></li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="alert alert-warning" style=" max-width:500px">
                                <strong>Warning!</strong> The used course materials are property of NTNU.
                                Usage and download are only allowed for the purpose of this course.
                                Copying and Sharing for other purposes is prohibited.
                            </div>

                        </div>
                    </div>
                </div></div>

            {% else %}

                No course materials are provided for this course yet.
                {% if request.user.is_teacher or request.user.is_superuser %}
                    You can add course materials now!
                    <br>
                    <div class="LPButton">
                        <a href="{% url 'course:upload_material' course_id=course.id %}">Upload course materials</a>
                    </div>
                {% endif %}

            {% endif %}
    </div>

    </div>


{% endblock courseTabContent %}

course/templates/course/course_page_content/course_quizzes.html
{% load to_class_name %}
{% load static %}

{% block courseTabContent %}
{# This content is displayed within a containing <div class="card">...</div> #}

    <div class="card-body">
        {% if tasks %}

            {% if request.user.is_teacher or request.user.is_superuser %}
                <div class="LPButton">
                    <a href="{% url 'course:task_selection' course.id %}">Browse existing tasks</a>
                </div>
                <div class="LPButton">
                    <a href="{% url 'task:new1' course_id=course.id %}">Add new task</a>
                </div>
            {% endif %}
            <br>
            <div class="card-text">
                <table class="table">
                    <thead class="thead-light"><tr>
                            <th>Name</th>
                            <th>Type</th>
                            <th>Attempt task</th>
                            {% if request.user.is_teacher or request.user.is_superuser %}
                                <th>Edit</th>
                                <th>Remove from course</th>
                            {% endif %}
                    </tr></thead>
                    {% for task in tasks %}
                        <tr>
                            <td><a href="{% url task.do_url task_id=task.id course_id=course.id slide_id=0 %}">{{ task.name }}</a></td>
                            <td>{{ task.type }}</td>
                            <td><a class="LPButton btn" style="margin: 0;" href="{% url task.do_url task_id=task.id course_id=course.id slide_id=0 %}">Do task</a>
                            </td>
                            {% if request.user.is_teacher or request.user.is_superuser %}
                                <td><a class="LPButton btn" style="margin: 0;" href="{% url task.edit_url task_id=task.id course_id=course.id %}">Edit</a></td>
                                <td><a class="LPButton btn remove_button" style="margin: 0;"
                                       data-course_id="{{ course.id }}" data-model_name="{{ task | to_class_name }}" data-instance_id="{{ task.id }}">
                                    Remove
                                </a></td>
                            {% endif %}
                        </tr>
                    {% endfor %}
                </table>
            </div>

        {% else %}

            <div class="card-text" style="text-align: left;">
                No tasks have been added to this course yet.
                {% if request.user.is_teacher or request.user.is_superuser %}
                    You can add some now!
                    <br>
                    <div class="LPButton">
                        <a href="{% url 'course:task_selection' course.id %}">Browse existing tasks</a>
                    </div>
                    <div class="LPButton">
                        <a  href="{% url 'task:new1' course_id=course.id %}">Add new task</a>
                    </div>
                {% endif %}
            </div>

        {% endif %}

    </div>

    <script>
    function activateSlides(){
           const triggerEl = document.querySelector('#myTab button[data-bs-target="#slides"]')
            var tab = bootstrap.Tab.getInstance(triggerEl)

        tab.show()

    }
    </script>





{% endblock courseTabContent %}

course/templates/course/course_page_content/course_slides.html
{% block courseTabContent %}
{# This content is displayed within a containing <div class="card">...</div> #}

    <div class="card-body">
        {% if slides %}
            {% if request.user.is_teacher or request.user.is_superuser %}
            <div class="LPButton">
                <a href="{% url 'course:slide_selection' course.id %}">Click here to add or remove slides</a>
            </div>
            {% endif %}
            <div class="card border-0" style="padding: 20px">
                {% include 'slide/grid_view_course.html' with course=course slides=slides %}
            </div>

        {% else %}

            <div class="card-text" style="text-align: left;">
                No slides have been added to this course yet.
                {% if request.user.is_teacher or request.user.is_superuser %}
                You can add some now!
                <br>
                <div class="LPButton">
                    <a href="{% url 'course:slide_selection' course.id %}">Click here to add slides</a>
                </div>
                {% endif %}
            </div>

        {% endif %}
    </div>

{% endblock courseTabContent %}

course/templates/course/course_page_content/learning_outcomes.html
{% block courseTabContent %}
{# This content is displayed within a containing <div class="card">...</div> #}

    <div class="card-body">
        {% if course.learning_outcomes %}

            <div class="card-text" style="text-align: left;">
                {% if request.user.is_teacher or request.user.is_superuser %}
                <div class="LPButton">
                    <a href="{% url 'course:edit_learning_outcomes' course.id  %}">Edit learning outcomes</a>
                </div>
                <br>
                {% endif %}
                <div class="card border-0">
                    <div class="card-body"><div class="card-text">
                        {{ course.learning_outcomes | safe }}
                    </div></div>
                </div>
            </div>

        {% else %}

            <div class="card-text" style="text-align: left">
                No learning outcomes are provided for this course yet.
                {% if request.user.is_teacher or request.user.is_superuser %}
                You can add learning outcomes now!
                <br>
                <div class="LPButton">
                    <a href="{% url 'course:edit_learning_outcomes' course.id  %}">Add learning outcomes</a>
                </div>
                {% endif %}
            </div>

        {% endif %}
    </div>
    
{% endblock courseTabContent %}