learnpathology/urls.py
from django.contrib import admin
from django.contrib.flatpages import views
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

import learnpathology.views
import slide.views

urlpatterns = [
    path('', learnpathology.views.index, name='frontpage'),
    path('privacy/', learnpathology.views.privacy_info, name='privacy'),
    path('viewer/<int:slide_id>/', slide.views.whole_slide_viewer, name="view_wsi"),
    path('viewer/tile/<int:slide_id>/<int:osd_level>/<int:x>/<int:y>/', slide.views.tile, name="tile"),
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('multiple_choice/', include('multiple_choice.urls')),
    path('slide/', include('slide.urls')),
    path('tag/', include('tag.urls')),
    path('course/', include('course.urls')),
    path('task/', include('task.urls')),
    path('comparison/', include('comparison.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('free_text/', include('free_text.urls')),
    path('click_question/', include('click_question.urls')),
    path('one_to_one/', include('one_to_one.urls')),
    path('annotation_task/', include('annotation_task.urls')),

    path('one_column/', learnpathology.views.test_one_column),
    path('two_column/', learnpathology.views.test_two_column),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.USE_FEIDE_LOGIN:
    urlpatterns += [path('accounts/', include('feide.urls')),]
    #urlpatterns += [path('accounts/', include('allauth.urls')),]

urlpatterns += [
    # Define specific paths (can be used with {% url %} tag
    # path('about/', views.flatpage, {'url': '/about/'}, name='about'),
    # path('privacy/', views.flatpage, {'url': '/privacy/'}, name='privacy'),

    # Or, use this 'catchall' pattern for all flatpages
    re_path(r'^(?P<url>.*/)$', views.flatpage),
]

slide/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib.auth import views as auth_views
import os
from learnpathology import settings
from slide import views

app_name = 'slide'
urlpatterns = [
    path('list/', views.index, name='list'),
    path('browser/', views.image_browser, name='browser'),
    path('browser/reset', views.reset_image_browser, name='browser_reset'),
    #path('browser/grid-view', views.grid_view, name='grid_view'),
    #path('browser/list-view', views.list_view, name='list_view'),
    path('view/<int:slide_id>/', views.whole_slide_view_full, name='view_full'),
    path('view/<int:slide_id>/<int:course_id>', views.whole_slide_view_full, name='view_full'),
    path('edit-tags/<int:slide_id>', views.edit_general_pathology_tags, name='edit_tags'),
    path('add-tag/', views.add_tag, name='add_tag'),
    path('remove-tag/', views.remove_tag, name='remove_tag'),
    # Annotation stuff
    path('annotation/create/', views.create_annotation, name='create_annotation'),
    path('annotation/update/', views.update_annotation, name='update_annotation'),
    path('annotation/delete/', views.delete_annotation, name='delete_annotation'),
    path('upload/', views.upload_slides, name='upload_slides'),
    path('upload/process/', views.process_uploaded_slides, name='process_uploads'),
    path('upload/view/', views.view_uploaded_slides, name='view_uploads'),
    path('edit/<int:slide_id>', views.edit_slide_metadata, name='edit_metadata'),
] + static('thumbnails/', document_root=settings.SLIDE_THUMBNAILS_DIR) \
  + static('uploads/thumbnails/', document_root=os.path.join(settings.TEMP_UPLOADED_SLIDE_DIR, 'thumbnails'))

tag/urls.py
from django.urls import path, include
from tag import views

app_name = 'tag'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('edit/<int:tag_id>/', views.edit, name='edit'),
    path('delete/<int:tag_id>/', views.delete, name='delete'),
]

task/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from task import views

app_name = 'task'
urlpatterns = [
    path('new1/', views.new1, name='new1'),
    path('new1/<int:course_id>', views.new1, name='new1'),
    path('new2/', views.new2, name='new2'),
    path('new2/<str:course_id>', views.new2, name='new2'),
    path('new3/<int:course_id>', views.new3, name='new3'),
    path('new3/', views.new3, name='new3'),
    path('list/', views.list, name='list'),
    path('list/<int:slide_id>', views.list, name='list'),
    path('delete/<int:task_id>/', views.delete, name='task_delete'),
    path('reset', views.reset_image_browser, name='reset'),
    path('reset/<int:course_id>', views.reset_image_browser, name='reset'),
]

slide/forms.py
import os
from django.core.exceptions import ValidationError
from django.db.models import TextField
from django.forms import ModelForm, ModelMultipleChoiceField, FileInput, \
    FileField, TextInput, Textarea
from slide.models import Slide
from tag.models import Tag


class SlideDescriptionForm(ModelForm):
    class Meta:
        model = Slide
        fields = ['long_description']
        exclude = ['name', 'description', 'path', 'image_file', 'pathology', 'organ_tags', 'stain_tags', 'other_tags']
        widgets = {
            'name': Textarea(attrs={'cols': '40', 'rows': '1', 'style': 'resize:none'}),
            'description': Textarea(attrs={'cols': '40', 'rows': '1', 'style': 'resize:none'}),
            'long_description': Textarea(attrs={'cols': '40', 'rows': '10'}),
        }


class SlideMetadataForm(ModelForm):
    class Meta:
        model = Slide
        fields = ['name', 'description', 'long_description', 'pathology', 'organ_tags', 'stain_tags', 'other_tags']
        widgets = {
            'description': Textarea(attrs={'cols': '40', 'rows': '1', 'style': 'resize:none'}),
            'long_description': Textarea(attrs={'cols': '40', 'rows': '10'}),
        }

    organ_tags = ModelMultipleChoiceField(
        queryset=Tag.objects.filter(is_organ=True).order_by('name'),
        required=True,
        label='Organ System',
    )
    stain_tags = ModelMultipleChoiceField(
        queryset=Tag.objects.filter(is_stain=True).order_by('name'),
        required=True,
        label='Stain',
    )
    other_tags = ModelMultipleChoiceField(
        queryset=Tag.objects.filter(is_organ=False, is_stain=False).order_by('name'),
        required=False,
        blank=True,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.instance and self.instance.pk:
            # Initial must have list of id, not a query sets
            self.fields['organ_tags'].initial = [x.pk for x in self.instance.tags.filter(is_organ=True)]
            self.fields['stain_tags'].initial = [x.pk for x in self.instance.tags.filter(is_stain=True)]
            self.fields['other_tags'].initial = [x.pk for x in self.instance.tags.filter(is_organ=False, is_stain=False)]

slide/views.py
import os.path
import json
import shutil
import string
import random
from os.path import join

import django.urls
import fast
from django.conf import settings
from django.contrib import messages
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponse, JsonResponse, HttpResponseNotFound
from django.shortcuts import render, redirect
from django.core.files.uploadedfile import UploadedFile
from django.views.decorators.cache import cache_page
from tag.models import Tag
from user.decorators import teacher_required, uploader_required
from slide.models import Slide, AnnotatedSlide, Annotation, SlideUpload
from slide.forms import SlideMetadataForm

GENERAL_PATHOLOGY_TAGS = (
    'inflammation', 'squamous cell carcinoma', 'adenocarcinoma', 'necrosis'
)


class SlideCache:
    """
    A class to keep a cache of slides in memory.
    """

    def __init__(self):
        # TODO load FAST once
        import fast
        # fast.Reporter.setGlobalReportMethod(fast.Reporter.COUT)
        test = fast.WholeSlideImageImporter.New() # Just to initialize FAST..
        self.slides = {}

    def load_slide_to_cache(self, slide_id):
        if slide_id not in self.slides:
            slide = Slide.objects.get(pk=slide_id)
            slide.load_image() # This will load slide with FAST, so it is ready to use
            self.slides[slide_id] = slide
        return self.slides[slide_id]

    def get_slide(self, slide_id):
        return self.slides[slide_id]

    def remove(self, slide_id):
        if slide_id in self.slides:
            del self.slides[slide_id]


# Initialize global slide cache as a global variable. This should only happen once..
slide_cache = SlideCache()


def index(request):
    slides = Slide.objects.all()

    # Filters
    organs = request.GET.getlist('organ[]')
    if len(organs) > 0: slides = slides.filter(tags__in=organs)
    stains = request.GET.getlist('stain[]')
    if len(stains) > 0: slides = slides.filter(tags__in=stains)
    tags = request.GET.getlist('tag[]')
    if len(tags) > 0: slides = slides.filter(tags__in=tags)
    selected_pathology = request.GET.get('pathology', False)
    selected_histology = request.GET.get('histology', False)
    if not selected_pathology and not selected_histology:
        selected_pathology = True
        selected_histology = True
    if selected_pathology and not selected_histology:
        slides = slides.filter(pathology=True)
    elif not selected_pathology and selected_histology:
        slides = slides.filter(pathology=False)

    # Handle search and search results
    if request.GET.get('submit_button') == 'Clear search':
        search_query = None
        search_result = None
    else:
        search_query = request.GET.get('search')
        if search_query is not None and len(search_query) > 0:
            filter_result = Slide.objects.filter(
                Q(name__contains=search_query) | Q(description__contains=search_query) | Q(long_description__contains=search_query)
            )
            search_result = filter_result
        else:
            search_query = None
            search_result = None

    return render(request, 'slide/index.html', {
        'slides': slides,
        'search_query': search_query,
        'search_result': search_result,
        'organ_tags': Tag.objects.filter(is_organ=True),
        'stain_tags': Tag.objects.filter(is_stain=True),
        'other_tags': Tag.objects.filter(is_organ=False, is_stain=False),
        'selected_organ_tags': organs,
        'selected_stain_tags': stains,
        'selected_other_tags': tags,
        'selected_pathology': selected_pathology,
        'selected_histology': selected_histology,
    })


def image_browser(request):
    """
    Set up the context for the image browser page.

    The logic here is to find the relevant slides based on the currently active filters,
    and if search has been applied to search only among those relevant slides.
    """

    last_url = request.headers.get('referer', '')
    prev_context = {} if ('slide/browser/' not in last_url) else request.session.get('image_browser_context', {})
    request.session['image_browser_context'] = {}
    # Initialize empty context dictionary
    context = {}

    # ==================================================================
    # Set up variables for which filtering options have been applied
    # ==================================================================
    organ_changed = ('organ-system' in request.GET)                     # Organ selection changed
    other_changed = ('other-tag' in request.GET)                     # Other tag selection changed
    general_path_changed = ('general_pathology_button' in request.GET)  # General pathology changed
    hist_path_changed = ('histology-pathology' in request.GET)          # Histology/pathology changed
    search_button_clicked = ('submit_button' in request.GET)            # Search query entered
    clear_search_clicked = ('clear_button' in request.GET)              # Search cleared

    # ==================================================================
    # Find selections for filtering options
    # ==================================================================
    # ORGAN FILTER
    if organ_changed:
        # Update the organ selection from the GET request
        selected_organ_tag_id = [request.GET.get('organ-system')]
    else:
        # Retrieve the previous organ selection or set to 'all'
        selected_organ_tag_id = prev_context['selected_organ_tag_ids'] if ('selected_organ_tag_ids' in prev_context) else ['all']
    if 'all' in selected_organ_tag_id:
        organ_tags = Tag.objects.filter(is_organ=True)
    else:
        organ_tags = Tag.objects.filter(is_organ=True, id__in=selected_organ_tag_id)

    # OTHER FILTER
    if other_changed:
        # Update the organ selection from the GET request
        selected_other_tag_id = [request.GET.get('other-tag')]
    else:
        # Retrieve the previous other selection or set to 'all'
        selected_other_tag_id = prev_context['selected_other_tag_ids'] if (
                    'selected_other_tag_ids' in prev_context) else ['all']
    if 'all' in selected_other_tag_id:
        other_tags = None
    else:
        other_tags = Tag.objects.filter(is_organ=False, is_stain=False, id__in=selected_other_tag_id)

    # HISTOLOGY/PATHOLOGY FILTER
    if hist_path_changed:
        # Update the histology_pathology variable from the GET request
        histology_pathology = request.GET.get('histology-pathology')

        selected_histology = (histology_pathology == 'histology')
        selected_pathology = (histology_pathology == 'pathology')
    else:
        # Retrieve the previous values or set to False
        selected_histology = prev_context['selected_histology'] if 'selected_histology' in prev_context else False
        selected_pathology = prev_context['selected_pathology'] if 'selected_pathology' in prev_context else False

    selected_both = (not selected_histology and not selected_pathology)

    # SEARCH FILTER
    if search_button_clicked:
        search_query = request.GET.get('search')
        if len(search_query) == 0:
            search_query = None
    elif clear_search_clicked:
        search_query = None
    else:
        try:
            search_query = prev_context['search_query']
        except KeyError as err:
            search_query = None

    # ==================================================================
    # Filter slides, and apply search if the search button was clicked
    # ==================================================================
    slides = Slide.objects.all()
    slides = slides.filter(tags__in=organ_tags)
    if other_tags is not None:
        slides = slides.filter(tags__in=other_tags)
    if not selected_both:
        slides = slides.filter(pathology=selected_pathology)
    if not (hist_path_changed and 'selected_general_pathology_ids' in prev_context):
        gen_path_tag_id = None
        if search_button_clicked and 'selected_general_pathology_ids' in prev_context:
            gen_path_tag_id = prev_context['selected_general_pathology_ids'][0]
        elif general_path_changed:
            gen_path_tag_id = int(request.GET.get('general_pathology_button').split('-')[-1])
        if gen_path_tag_id is not None:
            gen_path_tag = Tag.objects.get(id=gen_path_tag_id)
            slides = slides.filter(tags__in=[gen_path_tag])
            context['selected_general_pathology'] = gen_path_tag
            request.session['image_browser_context']['selected_general_pathology_ids'] = queryset_to_id_list(Tag.objects.filter(id=gen_path_tag_id))  # function takes queryset
    if search_query is not None:    # If search was updated, search among applicable_slides
        slides = slides.filter(Q(name__contains=search_query) | Q(description__contains=search_query) | Q(long_description__contains=search_query))

    # ==================================================================
    # Update context
    # ==================================================================
    context['slides'] = sorted(slides, key=lambda s: s.name)
    context['selected_organ_tag'] = ['all'] if 'all' in selected_organ_tag_id else Tag.objects.filter(id__in=selected_organ_tag_id)
    context['selected_other_tag'] = ['all'] if 'all' in selected_other_tag_id else Tag.objects.filter(id__in=selected_other_tag_id)
    context['selected_both'] = selected_both
    context['selected_histology'] = selected_histology
    context['selected_pathology'] = selected_pathology
    context['search_query'] = search_query
    context['organ_tags'] = Tag.objects.filter(is_organ=True).order_by('name')
    context['other_tags'] = Tag.objects.filter(is_organ=False, is_stain=False).order_by('name')

slide/templates/slide/grid_cards/card_base.html
{% load static %}
<div class="slideGridViewCard card" style="border: 1px solid lightgrey;">

    {# Image display #}
    {% if course %} <a class="cardImageHeader card border-0" href="{% url 'slide:view_full' slide.id  course.id  %}">
    {% else %}
    <a class="cardImageHeader card border-0" href="{% url 'slide:view_full' slide.id %}">{% endif %}
        <div class="card transparentBackground border-0 w-100 h-100">
            <div class="headerImageContainer card">
                <img loading="lazy" class="headerImage" src="/slide/thumbnails/{{ slide.id }}.jpg" alt="WSI thumbnail for {{ slide.name }}">
                <!-- Use below line to crop image to fit the header container -->
                {# <img class="headerImage croppedImage" src="/slide/thumbnails/{{ slide.id }}.jpg" alt="WSI thumbnail"> #}
            </div>
        </div>
    </a>

    {# Card content (slide name, description, buttons, ...) #}
    <div class="gridCardContent">
    {% if course %} <a class="card noLinkStyling border-0" href="{% url 'slide:view_full' slide.id course.id %}">
        {% else %}
         <a class="card noLinkStyling border-0" href="{% url 'slide:view_full' slide.id %}"> {% endif %}
            <h3 class="card-title">{{ slide.name }} </h3>

            <p class="card-subtitle" style="font-size: medium;">
                <span class="body-text">{{ slide.description }}</span>
              {% if request.user.is_superuser or request.user.is_uploader %}
              <a href="{% url 'slide:edit_metadata' slide.id %}" title="Edit slide metadata">
                <button class="custom-button btn btn-secondary" style="margin-left: auto; float: right;">
                    <div class="button-icon">
                        <span class="iconify" data-icon="fluent:edit-12-regular" data-width="24" data-height="24"></span>
                    </div>
                </button>
              </a>
            {% endif %}
            </p>
            {% block gridCardQuestions %}
            {% endblock gridCardQuestions %}
        </a>
    </div>

</div>

slide/templates/slide/grid_cards/card_base_slide_selection.html
{% load bootstrap_icons %}
{% load to_class_name %}


<div class="slideGridViewCard card {% if add_border == 'true' %}remove_button border-success{% else %}add_button{% endif %}"
     style="max-height: 300px;{% if add_border == 'true' %} border-width: 3px;{% endif %}"
     data-course_id={{ course.id }} data-model_name={{ slide | to_class_name }} data-instance_id={{ slide.id }}>

    {# Image display #}
    <a class="cardImageHeader card border-0">
        <div class="card transparentBackground border-0 w-100 h-100" style="float: left;">
            <div class="headerImageContainer card">
                <img class="headerImage" src="/slide/thumbnails/{{ slide.id }}.jpg" alt="WSI thumbnail for {{ slide.name }}">
                <!-- Use below line to crop image to fit the header container -->
{#                 <img class="headerImage croppedImage" src="/slide/thumbnails/{{ slide.id }}.jpg" alt="WSI thumbnail"> #}
            </div>
        </div>

        {% if add_border == 'true' %}
            <div style="float: right; position: absolute; top: 5px; right: 5px;">
                <svg class="bi text-success" width="32px" height="32px" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
                    {% bs_icon 'check-circle' %}
                </svg>
            </div>
        {% endif %}
    </a>

    {# Card content (slide name, description, buttons, ...) #}
    <div class="gridCardContent">
        <a class="card noLinkStyling border-0">
            <h5 class="card-title">{{ slide.name }}</h5>
            <p class="card-subtitle" style="font-size: medium;">{{ slide.description }}</p>
{#            {% block gridCardQuestions %}#}
{#            {% endblock gridCardQuestions %}#}
        </a>
    </div>

</div>

slide/templates/slide/grid_cards/grid_card.html
<div class="slideGridViewCard card" style="max-height: 400px;">

    {# Image display #}
    <a class="cardImageHeader card border-0" href="{% url 'slide:view_full' slide.id %}">
        <div class="card transparentBackground border-0 w-100 h-100">
            <div class="headerImageContainer card">
                <img class="headerImage" src="/slide/thumbnails/{{ slide.id }}.jpg">
            </div>
        </div>
    </a>

    {# Card content (slide name, description, buttons, ...) #}
    <div class="card border-0 h-50" style="padding: 5%">
        <h5 class="card-title">{{ slide.name }}</h5>
        <p class="card-subtitle">{{ slide.description }}</p>
        {% block gridCardQuestions %}
        {% endblock gridCardQuestions %}
    </div>

</div>

slide/templates/slide/grid_cards/grid_card_course.html
{% extends 'slide/grid_cards/card_base.html' %}

{% load to_class_name %}

{% block gridCardQuestions %}

    {% if request.user.is_teacher or request.user.is_superuser %}

        <div class="card-content" style="padding-top: 5px">
            <a class="LPButton btn" href="{% url 'course:new_task_and_add' course_id=course.id slide_id=slide.id %}" style="margin: 0;">
                Create new task
            </a>
        </div>
             <div class="card-content" style="padding-top: 5px">
            <a class="LPButton btn remove_button" style="margin: 0;"
               data-course_id={{ course.id }} data-model_name={{ slide | to_class_name }} data-instance_id={{ slide.id }}>
                Remove slide
            </a>
        </div>
    {% endif %}

{% endblock gridCardQuestions %}

slide/templates/slide/grid_cards/grid_card_minimal.html
{% extends 'slide/grid_cards/card_base.html' %}

{% block gridCardQuestions %}

{% endblock gridCardQuestions %}

slide/templates/slide/grid_cards/grid_card_new_task.html
{% extends 'slide/grid_cards/card_base.html' %}

{% block gridCardQuestions %}

    {% if request.user.is_teacher or request.user.is_superuser %}
        {% if course_id %}
            <a class="LPButton btn" href="{% url 'task:new' slide_id=slide.id course_id=course_id %}" style="margin-top: auto;">Create new task</a>
        {% else %}
            <a class="LPButton btn" href="{% url 'task:new' slide_id=slide.id %}" style="margin-top: auto;">Create new task</a>
        {% endif %}
    {% endif %}

{% endblock gridCardQuestions %}

slide/templates/slide/grid_cards/grid_card_slide_selection.html
{% load to_class_name %}
{% load static %}


<div class="slideGridViewCard card {% if slide_selected == 'true' %}remove_button border-success{% else %}add_button{% endif %}"
     style="max-height: {{ max_card_height }}px; border: {% if slide_selected == 'true' %}3px solid{% else %}1px solid lightgrey{% endif %};"
     data-course_id={{ course.id }} data-model_name={{ slide | to_class_name }} data-instance_id={{ slide.id }}>

    {# Image display #}
    <a class="cardImageHeader card border-0">
        <div class="card transparentBackground border-0 w-100 h-100" style="float: left;">
            <div class="headerImageContainer card">
                <img loading="lazy" class="headerImage" src="/slide/thumbnails/{{ slide.id }}.jpg" alt="WSI thumbnail for {{ slide.name }}">
                <!-- Use below line to crop image to fit the header container -->
{#                 <img class="headerImage croppedImage" src="/slide/thumbnails/{{ slide.id }}.jpg" alt="WSI thumbnail"> #}
            </div>
        </div>

        {% if slide_selected == 'true' %}
            <div style="float: right; position: absolute; top: 5px; right: 5px;">
                <svg class="bi text-success" width="32px" height="32px" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg">
                    {% include 'svg_icons/check-circle.svg' %}">
                </svg>
            </div>
        {% endif %}
    </a>

    {# Card content (slide name, description, buttons, ...) #}
    <div class="gridCardContent">
        <a class="card noLinkStyling border-0">
            <h3 class="card-title">{{ slide.name }}</h3>
            <p class="card-subtitle" style="font-size: medium;">{{ slide.description }}</p>
{#            {% block gridCardQuestions %}#}
{#            {% endblock gridCardQuestions %}#}
        </a>
    </div>

</div>

slide/templates/slide/grid_cards/slide_selection_add.html
{% extends 'slide/grid_cards/grid_card_slide_selection.html' %}
{% load to_class_name %}

{% block gridCardQuestions %}

    {% if request.user.is_teacher or request.user.is_superuser %}
        <div class="card-content" style="padding-top: 5px">
            <a class="LPButton btn add_button" style="margin: 0;"
               data-course_id={{ course.id }} data-model_name={{ slide | to_class_name }} data-instance_id={{ slide.id }}>
                Add slide
            </a>
        </div>
    {% endif %}

{% endblock gridCardQuestions %}

slide/templates/slide/grid_cards/slide_selection_remove.html
{% extends 'slide/grid_cards/grid_card_slide_selection.html' %}
{% load to_class_name %}

{% block gridCardQuestions %}

    {% if request.user.is_teacher or request.user.is_superuser %}
        <div class="card-content" style="padding-top: 5px">
            <a class="LPButton btn remove_button" style="margin: 0;"
               data-course_id={{ course.id }} data-model_name={{ slide | to_class_name }} data-instance_id={{ slide.id }}>
                Remove slide
            </a>
        </div>
    {% endif %}

{% endblock gridCardQuestions %}